export enum Faces {
    AXE = 'AXE',

    ARROW = 'ARROW',
    ARROW_BORDERED = 'ARROW_BORDERED',

    HELMET = 'HELMET',
    HELMET_BORDERED = 'HELMET_BORDERED',

    SHIELD = 'SHIELD',
    SHIELD_BORDERED = 'SHIELD_BORDERED',

    HAND = 'HAND',
    HAND_BORDERED = 'HAND_BORDERED'
}
